### ISSUE TITLE
Erro upon lein run migrate

### ISSUE THREAD

**Issue by maacl** [yogthos/memory-hole#8]
I am using PG 8.4. I get the following:
```

➜  memory-hole git:(master) lein run migrate 
2016-08-29 09:34:53,311 [main] INFO  migratus.core - Starting migrations 
2016-08-29 09:34:53,736 [main] INFO  migratus.database - creating migration table 'schema_migrations' 
2016-08-29 09:34:53,876 [main] INFO  migratus.core - Running up for [100 200 400 500 600 700] 
2016-08-29 09:34:53,878 [main] INFO  migratus.core - Up 100-users 
2016-08-29 09:34:53,921 [main] ERROR migratus.database - failed to execute command:
 CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;
 
 
org.postgresql.util.PSQLException: ERROR: syntax error at or near "EXTENSION"
  Position: 8
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2310) ~[postgresql-9.4.1209.jar:9.4.1209]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2023) ~[postgresql-9.4.1209.jar:9.4.1209]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:217) ~[postgresql-9.4.1209.jar:9.4.1209]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:421) ~[postgresql-9.4.1209.jar:9.4.1209]
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:166) ~[postgresql-9.4.1209.jar:9.4.1209]
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:137) ~[postgresql-9.4.1209.jar:9.4.1209]
	at clojure.java.jdbc$db_do_execute_prepared_statement$fn__34004.invoke(jdbc.clj:784) ~[na:na]
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:637) [na:na]
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585) [na:na]
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:598) [na:na]
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585) [na:na]
	at clojure.java.jdbc$db_do_execute_prepared_statement.invokeStatic(jdbc.clj:783) ~[na:na]
	at clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:778) ~[na:na]
	at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:814) ~[na:na]
	at clojure.java.jdbc$db_do_prepared.invoke(jdbc.clj:795) ~[na:na]
	at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:802) ~[na:na]
	at clojure.java.jdbc$db_do_prepared.invoke(jdbc.clj:795) ~[na:na]
	at migratus.database$up_STAR_$fn__39711$fn__39720.invoke(database.clj:76) ~[na:na]
	at migratus.database$up_STAR_$fn__39711.invoke(database.clj:75) [na:na]
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:613) [na:na]
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585) [na:na]
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:598) [na:na]
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585) [na:na]
	at migratus.database$up_STAR_.invokeStatic(database.clj:68) [na:na]
	at migratus.database$up_STAR_.invoke(database.clj:67) [na:na]
	at migratus.database.Migration.up(database.clj:206) [na:na]
	at migratus.core$up_STAR_.invokeStatic(core.clj:47) [na:na]
	at migratus.core$up_STAR_.invoke(core.clj:45) [na:na]
	at migratus.core$migrate_up_STAR_.invokeStatic(core.clj:55) [na:na]
	at migratus.core$migrate_up_STAR_.invoke(core.clj:49) [na:na]
	at migratus.core$migrate_STAR_.invokeStatic(core.clj:61) [na:na]
	at migratus.core$migrate_STAR_.invoke(core.clj:59) [na:na]
	at migratus.core$run.invokeStatic(core.clj:25) [na:na]
	at migratus.core$run.invoke(core.clj:21) [na:na]
	at migratus.core$migrate.invokeStatic(core.clj:66) [na:na]
	at migratus.core$migrate.invoke(core.clj:63) [na:na]
	at luminus_migrations.core$migrate.invokeStatic(core.clj:48) [na:na]
	at luminus_migrations.core$migrate.invoke(core.clj:25) [na:na]
	at memory_hole.core$_main.invokeStatic(core.clj:59) [na:na]
	at memory_hole.core$_main.doInvoke(core.clj:54) [na:na]
	at clojure.lang.RestFn.invoke(RestFn.java:408) [clojure-1.8.0.jar:na]
	at clojure.lang.Var.invoke(Var.java:379) [clojure-1.8.0.jar:na]
	at user$eval40423.invokeStatic(form-init489971274304859740.clj:1) [na:na]
	at user$eval40423.invoke(form-init489971274304859740.clj:1) [na:na]
	at clojure.lang.Compiler.eval(Compiler.java:6927) [clojure-1.8.0.jar:na]
	at clojure.lang.Compiler.eval(Compiler.java:6917) [clojure-1.8.0.jar:na]
	at clojure.lang.Compiler.load(Compiler.java:7379) [clojure-1.8.0.jar:na]
	at clojure.lang.Compiler.loadFile(Compiler.java:7317) [clojure-1.8.0.jar:na]
	at clojure.main$load_script.invokeStatic(main.clj:275) [clojure-1.8.0.jar:na]
	at clojure.main$init_opt.invokeStatic(main.clj:277) [clojure-1.8.0.jar:na]
	at clojure.main$init_opt.invoke(main.clj:277) [clojure-1.8.0.jar:na]
	at clojure.main$initialize.invokeStatic(main.clj:308) [clojure-1.8.0.jar:na]
	at clojure.main$null_opt.invokeStatic(main.clj:342) [clojure-1.8.0.jar:na]
	at clojure.main$null_opt.invoke(main.clj:339) [clojure-1.8.0.jar:na]
	at clojure.main$main.invokeStatic(main.clj:421) [clojure-1.8.0.jar:na]
	at clojure.main$main.doInvoke(main.clj:384) [clojure-1.8.0.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:421) [clojure-1.8.0.jar:na]
	at clojure.lang.Var.invoke(Var.java:383) [clojure-1.8.0.jar:na]
	at clojure.lang.AFn.applyToHelper(AFn.java:156) [clojure-1.8.0.jar:na]
	at clojure.lang.Var.applyTo(Var.java:700) [clojure-1.8.0.jar:na]
	at clojure.main.main(main.java:37) [clojure-1.8.0.jar:na]
2016-08-29 09:34:53,926 [main] INFO  migratus.core - Ending migrations 
Exception in thread "main" org.postgresql.util.PSQLException: ERROR: syntax error at or near "EXTENSION"
  Position: 8, compiling:(/tmp/form-init489971274304859740.clj:1:72)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "EXTENSION"
  Position: 8
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2310)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2023)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:217)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:421)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:166)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:137)
	at clojure.java.jdbc$db_do_execute_prepared_statement$fn__34004.invoke(jdbc.clj:784)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:637)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:598)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
	at clojure.java.jdbc$db_do_execute_prepared_statement.invokeStatic(jdbc.clj:783)
	at clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:778)
	at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:814)
	at clojure.java.jdbc$db_do_prepared.invoke(jdbc.clj:795)
	at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:802)
	at clojure.java.jdbc$db_do_prepared.invoke(jdbc.clj:795)
	at migratus.database$up_STAR_$fn__39711$fn__39720.invoke(database.clj:76)
	at migratus.database$up_STAR_$fn__39711.invoke(database.clj:75)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:613)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:598)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
	at migratus.database$up_STAR_.invokeStatic(database.clj:68)
	at migratus.database$up_STAR_.invoke(database.clj:67)
	at migratus.database.Migration.up(database.clj:206)
	at migratus.core$up_STAR_.invokeStatic(core.clj:47)
	at migratus.core$up_STAR_.invoke(core.clj:45)
	at migratus.core$migrate_up_STAR_.invokeStatic(core.clj:55)
	at migratus.core$migrate_up_STAR_.invoke(core.clj:49)
	at migratus.core$migrate_STAR_.invokeStatic(core.clj:61)
	at migratus.core$migrate_STAR_.invoke(core.clj:59)
	at migratus.core$run.invokeStatic(core.clj:25)
	at migratus.core$run.invoke(core.clj:21)
	at migratus.core$migrate.invokeStatic(core.clj:66)
	at migratus.core$migrate.invoke(core.clj:63)
	at luminus_migrations.core$migrate.invokeStatic(core.clj:48)
	at luminus_migrations.core$migrate.invoke(core.clj:25)
	at memory_hole.core$_main.invokeStatic(core.clj:59)
	at memory_hole.core$_main.doInvoke(core.clj:54)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:379)
	at user$eval40423.invokeStatic(form-init489971274304859740.clj:1)
	at user$eval40423.invoke(form-init489971274304859740.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	... 14 more
```

**Comment by maacl** [comment]
This is apparently related to PG 8.4, which I believed came with citext in core. With PG 9.5 it works.

**Comment by yogthos** [comment]
👍
